language: java
sudo: false
dist: trusty
group: beta
install: true
cache:
  directories:
    - $HOME/.m2/repository
env:
  global:
    - MAVEN_OPTS="-Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
script:
  - mvn -B clean install && mvn -B javadoc:javadoc
